name : Debug Variables

on: [workflow_dispatch]

jobs:
  setup:
    name: Setup Variables
    runs-on: ubuntu-latest
    steps:
      - name: Set Start Time
        run: echo "START_TIME=$(TZ=":Europe/Paris" date +'%Y_%m_%d_%H_%M_%S')" >> $GITHUB_ENV
      - name: Echo current date
        run: echo "$START_TIME"

      - name: Set Repo Name
        run: echo "REPO_NAME=${{ github.repository }}" >> $GITHUB_ENV
      - name: Echo repo name
        run: echo $REPO_NAME